Add controllers
Ben1t0/java-shareit pull request #1
Opened 2022-07-01 22:17 UTC by Ben1t0

2022-07-03 09:38 UTC, kukolev requested changes

2022-07-03 09:38 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +/**
Этот комментарий никак не помогает анализировать код. Бесполезные комментарии нужно удалять, чтобы не мешали.

2022-07-03 09:38 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +/**
Этот комментарий никак не помогает анализировать код. Бесполезные комментарии нужно удалять, чтобы не мешали.

2022-07-03 09:38 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> + * // TODO .
Здесь не хватает информации о том, что класс будет реализован в будущем в следующих спринтах.

2022-07-03 09:38 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +public class BookingServiceImpl implements BookingService {
Здесь не хватает TODO с информацией о том, что класс будет реализован в будущем в следующих спринтах.

2022-07-03 09:38 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/storage/BookingRepository.java
> +public interface BookingRepository {
Здесь не хватает TODO с информацией о том, что класс будет реализован в будущем в следующих спринтах.

2022-07-03 09:38 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>  /**
Этот комментарий никак не помогает анализировать код. Бесполезные комментарии нужно удалять, чтобы не мешали.

2022-07-03 09:38 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    void isUserExists(long id) {
Нарушение кодстайла: Название метода лучше начинать с глагола, обозначающего действие над аргументами или над классом, которому принадлежит метод. Так назначение метода будет понятно сразу из названия. Нужно поправить.

Также, судя по всему название скопировано из UserServiceImpl. Нужно поправить.

2022-07-03 09:38 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    void isUserExists(long id) {
Метод нужно сделать приватным, т.к. он является вспомогательными и не нужно, чтобы к нему был доступ извне.

2022-07-03 09:38 UTC, kukolev commented on src/main/java/ru/practicum/shareit/requests/controller/ItemRequestController.java
> +/**
Здесь не хватает информации о том, что класс будет реализован в будущем в следующих спринтах.

2022-07-03 09:38 UTC, kukolev commented on src/main/java/ru/practicum/shareit/requests/service/ItemRequestService.java
> +public interface ItemRequestService {
Здесь не хватает TODO с информацией о том, что класс будет реализован в будущем в следующих спринтах.

2022-07-03 09:38 UTC, kukolev commented on src/main/java/ru/practicum/shareit/requests/service/ItemRequestServiceImpl.java
> +public class ItemRequestServiceImpl implements ItemRequestService {
Здесь не хватает TODO с информацией о том, что класс будет реализован в будущем в следующих спринтах.

2022-07-03 09:38 UTC, kukolev commented on src/main/java/ru/practicum/shareit/requests/storage/ItemRequestRepository.java
> +public interface ItemRequestRepository {
Здесь не хватает TODO с информацией о том, что класс будет реализован в будущем в следующих спринтах.

2022-07-04 14:48 UTC, Ben1t0 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    void isUserExists(long id) {
поменял название, но метод именно пользователя проверяет в этом контроллере, чтобы когда создается Item убедится что существует в базе такой пользователь для поля Owner

2022-07-04 21:52 UTC, kukolev approved these changes

2022-07-05 08:41 UTC, merged