Add bookings
Ben1t0/java-shareit pull request #2
Opened 2022-07-21 20:02 UTC by Ben1t0

2022-07-22 17:01 UTC, kukolev requested changes

2022-07-22 17:01 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        return BookingMapper.toBookingDto(bookingService.createBooking(bookingDtoCreate));
Маппинг это задача сервиса. Нужно переместить маппинг в сервис.

2022-07-22 17:01 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        bookingDtoCreate.setRequesterId(requesterId);
Присвоение айди это бизнес-логика, которая должна быть в сервисе, а не в контроллере. Нужно перенести в сервис.

2022-07-22 17:01 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/model/BookingState.java
> +@ToString
Эта аннотация тут точно нужна? По моему енумы и так хорошо выводятся во встроенном toString().

2022-07-22 17:01 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/storage/BookingRepository.java
> +    Booking findFirstByItemIdAndEndBeforeOrderByEndDesc(Long itemId, LocalDateTime localDateTime);
По моему эти методы тоже лучше упростить с помощью @Query. Тогда название можно будет сделать меньше, чтобы просто отражало назначение метода.

2022-07-22 17:01 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +                .map(ItemMapper::toDtoWithBookings)
Этот код является бизнес-логикой приложения. Бизнес-логика должна быть вынесена в сервис.

2022-07-22 17:01 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/storage/BookingRepository.java
> +    Collection<Booking> findAllByBookerIdOrderByStartDesc(Long bookerId);
По моему эти методы тоже лучше упростить с помощью @query. Тогда название можно будет сделать меньше, чтобы просто отражало назначение метода.

2022-07-22 20:31 UTC, Ben1t0 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        return BookingMapper.toBookingDto(bookingService.createBooking(bookingDtoCreate));
То есть единственная задача контроллера это вызвать нужный метод сервиса ?

2022-07-22 20:57 UTC, Ben1t0 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        bookingDtoCreate.setRequesterId(requesterId);
Это же наполнение объекта перед передачей в сервис? Эта ДТОха нужна только для создания объекта, просто запаковал id перед тем как в сервис передать. Нужно обязательно как параметр передавать этот id в bookingService.createBooking ?

2022-07-22 21:36 UTC, Ben1t0 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        return BookingMapper.toBookingDto(bookingService.createBooking(bookingDtoCreate));
upd: перенес

2022-07-22 21:42 UTC, Ben1t0 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        bookingDtoCreate.setRequesterId(requesterId);
Перенес, но теперь из-за того что логику в сервис перенес у меня возникли циклические бины и Item приходится добывать в контроллере и передавать в сервис букинга

2022-07-23 11:10 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        bookingDtoCreate.setRequesterId(requesterId);
Не понятно, зачем нужно присваивать requesterId в коде, если можно отдать это фронту? Пусть фронт присылает ДТО с уже проставленным Id.

Циклические зависимости говорят о проблемах в дизайне классов. Нужно разобраться с этим и поправить.

2022-07-23 11:15 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public Collection<ItemDtoWithBookings> getAllByOwnerId(Long ownerId) {
По моему этому методу место в BookingService. Тогда не будет циклических зависимостей и ItemService можно будет добавить в BookingService. В свою очередь это поможет избавиться от лишнего кода в контроллере.

2022-07-23 11:15 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public ItemDtoWithBookings getItemByIdWithBookingsOrThrow(Long itemId, Long requesterId) {
По моему этому методу место в BookingService. Тогда не будет циклических зависимостей и ItemService можно будет добавить в BookingService. В свою очередь это поможет избавиться от лишнего кода в контроллере.

2022-07-23 11:15 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        return BookingMapper.toBookingDto(bookingService.createBooking(bookingDtoCreate));
Задача контроллера это принять данные и отправить в сервис. Большую часть этой работы делает фреймворк, поэтому остается просто вызвать нужный метод сервиса.

2022-07-23 11:17 UTC, kukolev requested changes

2022-07-23 11:17 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        Item item = itemService.getItemByIdOrThrow(bookingDtoCreate.getItemId());
Item это доменная модель. Контроллер не должен знать о доменной модели. Нужно перенести это код в сервис. Для этого нужно поправить ситуацию с циклическими зависимостями.

2022-07-23 15:57 UTC, Ben1t0 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        bookingDtoCreate.setRequesterId(requesterId);
Так задачу поставили, что ID пользователя прилетает через header.

2022-07-24 19:47 UTC, Ben1t0 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public Collection<ItemDtoWithBookings> getAllByOwnerId(Long ownerId) {
Эти два метода оставил на месте, ведь они возвращают коллекцию вещей, пусть они и запрашивают бронирования по ним

2022-07-25 07:31 UTC, kukolev requested changes

2022-07-25 07:31 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    private final ItemService itemService;
Поле нигде не используется. Неиспользуемый код нужно убирать, чтобы не отвлекал.

2022-07-25 07:31 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (item.getOwner().getId().equals(userId)) {
Валидации лучше вынести в отдельный приватный метод, так код будет читаться проще.

2022-07-25 07:31 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (!booking.getItem().getOwner().getId().equals(approverId)) {
Валидации лучше вынести в отдельный приватный метод, так код будет читаться проще.

2022-07-25 17:18 UTC, kukolev requested changes

2022-07-25 17:18 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (isItemOwner(item, userId)) {
В этом методе, начиная с этой строчки все еще есть валидации. Валидации лучше сделать в отельном методе, так метод будет менее нагруженным. Валидацию входного ДТО при этом следует вынести в начало метода, т.к. если ДТО не валидно, то не имеет смысла загружать booking и item из БД. 

Выглядеть это может примерно так:

```
public BookingDto createBooking(BookingDtoCreate bookingDtoCreate, Long userId) {        
        validateBookingCreateDto(bookingDtoCreate);

        User booker = userService.getUserByIdOrThrow(userId);
        Item item = itemRepository.findById(bookingDtoCreate.getItemId())
                .orElseThrow(() -> new ItemNotFoundException(bookingDtoCreate.getItemId()));

        validateItem(item, userId);
        Booking booking = Booking.builder()
                .status(BookingStatus.WAITING)
                .start(bookingDtoCreate.getStart())
                .end(bookingDtoCreate.getEnd())
                .booker(booker)
                .item(item)
                .build();
        return BookingMapper.toBookingDto(bookingRepository.save(booking));
}

```

2022-07-25 19:02 UTC, Ben1t0 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (isItemOwner(item, userId)) {
Понял, спасибо! Перенес.

2022-07-26 07:23 UTC, kukolev approved these changes

2022-07-26 08:23 UTC, merged