Add item requests
Ben1t0/java-shareit pull request #3
Opened 2022-08-09 22:07 UTC by Ben1t0

2022-08-14 07:11 UTC, kukolev requested changes

2022-08-14 07:11 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        BookingState bookingState;
Этот код маппинга состояния повторяется здесь и в следующем методе. Лучше вынести эту логику в отдельный приватный метод или в отдельный маппер, чтобы не дублировать код.

2022-08-14 07:11 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplIntegrationTest.java
> +        Thread.sleep(1000);
Эта задержка не имеет смысла, т.к. код выполняется в одном потоке. Лишний код нужно удалять, чтобы не отвлекал.

2022-08-14 07:11 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/controller/ItemControllerTest.java
> +    ObjectMapper mapper;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-08-14 07:11 UTC, kukolev commented on src/test/java/ru/practicum/shareit/request/controller/ItemRequestControllerTest.java
> +    ObjectMapper mapper;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.м

2022-08-14 17:55 UTC, Ben1t0 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        BookingState bookingState;
готово

2022-08-14 17:56 UTC, Ben1t0 commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplIntegrationTest.java
> +        Thread.sleep(1000);
там задержка нужна чтобы букинг стал в прошлом , потому что положить в базу букинг сразу в прошлое сервис не даст, я его кладу, жду секунду и проверяю. Можно только попробовать уменьшить слип раза в 2

2022-08-14 18:20 UTC, Ben1t0 commented on src/test/java/ru/practicum/shareit/item/controller/ItemControllerTest.java
> +    ObjectMapper mapper;
готово

2022-08-14 19:30 UTC, Ben1t0 commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplIntegrationTest.java
> +        Thread.sleep(1000);
изменил, постарался "прижать" время бронирования к текущему, но гарантий нет, если на какой то системе программа справится с записью в базу быстрее чем за 5 мс тест не пройдет

2022-08-15 07:34 UTC, kukolev requested changes

2022-08-15 07:34 UTC, kukolev commented on src/main/resources/application.properties
> +#spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-08-15 07:34 UTC, kukolev commented on src/main/resources/application.properties
> +#logging.level.org.springframework.transaction.interceptor=TRACE
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-08-15 08:15 UTC, Ben1t0 commented on src/main/resources/application.properties
> +#logging.level.org.springframework.transaction.interceptor=TRACE
готово

2022-08-16 06:20 UTC, kukolev approved these changes

2022-08-16 06:47 UTC, merged