add docker
Ben1t0/java-shareit pull request #4
Opened 2022-08-20 23:11 UTC by Ben1t0

2022-08-21 20:22 UTC, kukolev requested changes

2022-08-21 20:22 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/ShareItGateway.java
> +	public static void main(String[] args) {
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-08-21 20:22 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +            @RequestParam(name = "state", defaultValue = "all") String stateParam,
Можно сделать параметр stateParam не String, а BookingState. Тогда не нужно будет мапить их строки. Код будет проще.

Аналогично нужно поправить ниже.

2022-08-21 21:15 UTC, Ben1t0 commented on gateway/src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +            @RequestParam(name = "state", defaultValue = "all") String stateParam,
это вынесено чтобы можно было поймать исключение и выдать 400й код и соответствующее сообщение

2022-08-21 21:17 UTC, Ben1t0 commented on gateway/src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +            @RequestParam(name = "state", defaultValue = "all") String stateParam,
Валидация этого енума была уже в образце гейтвея от авторов задания, я просто поменял свое исключение и хендлер прописал.

2022-08-23 06:50 UTC, kukolev requested changes

2022-08-23 06:50 UTC, kukolev commented on server/src/test/java/ru/practicum/shareit/item/service/CommentServiceImplTest.java
> +        Thread.sleep(50);
Эта задержка здесь точно нужна? По моему она лишняя, т.к. код не многопоточный и нет смысла в остановке потока. Думаю, эту строку можно удалить.

2022-08-23 06:50 UTC, kukolev commented on .run/ShareItGateway.run.xml
> +<component name="ProjectRunConfigurationManager">
Этот файл не относится к исходному коду проекта. Все лишние файлы нужно удалить из пул-реквеста.

2022-08-23 06:50 UTC, kukolev commented on .run/ShareItServer.run.xml
> +<component name="ProjectRunConfigurationManager">
Этот файл не относится к исходному коду проекта. Все лишние файлы нужно удалить из пул-реквеста.

2022-08-23 06:53 UTC, Ben1t0 commented on server/src/test/java/ru/practicum/shareit/item/service/CommentServiceImplTest.java
> +        Thread.sleep(50);
Без неё тесты не проходят, в постмане стоит задержка перед тестом, а как здесь поставить по другому не знаю. Иначе букинг не успевает стать "прошедшим"

2022-08-23 06:54 UTC, Ben1t0 commented on .run/ShareItGateway.run.xml
> +<component name="ProjectRunConfigurationManager">
Не знал, они были в образцовом проекте, сейчас уберу, их IDEA генерит для своих нужд?

2022-08-23 15:59 UTC, kukolev commented on .run/ShareItGateway.run.xml
> +<component name="ProjectRunConfigurationManager">
Это файлы в которых прописаны параметры запуска приложения - что запускать, с какими параметрами и т.п.

2022-08-23 16:02 UTC, kukolev approved these changes

2022-08-23 16:46 UTC, merged